### ISSUE TITLE
Consolidate Configuration For Easier Customization

### ISSUE THREAD

**Issue by slucero** [forumone/web-starter#149]
Currently the configuration of individual vagrant machines and their provisioning is consolidated into a handful of places, but most of these are deeply nested into the folder structure and require pre-existing knowledge to find and adjust them.
This could be simplified by following a model set by the [Laravel Homestead](http://laravel.com/docs/5.1/homestead#configuring-homestead) VM project where they have consolidated all of their configuration into a single `Homestead.yaml` file at the root of the project.
This would require parsing of the configuration file in various places, including `Vagrantfile` and the Puppet configuration, but it would offer a greatly simplified developer experience when reviewing or customizing a project.
## Example `Homestead.yaml` Configuration File

``` yaml

---
ip: "192.168.10.10"
memory: 2048
cpus: 1
hostname: api
name: api
provider: virtualbox

authorize: ~/.ssh/id_rsa.pub

keys:
    - ~/.ssh/id_rsa

folders:
    - map: "."
      to: "/home/vagrant/lumen"

sites:
    - map: api.app
      to: "/home/vagrant/lumen/public"

databases:
    - homestead

variables:
    - key: APP_ENV
      value: local

# blackfire:
#     - id: foo
#       token: bar
#       client-id: foo
#       client-token: bar

ports:
    - send: 8000
      to: 80
#     - send: 7777
#       to: 777
#       protocol: udp
```
