### ISSUE TITLE
Clarify support for multiple hostnames/databases

### ISSUE THREAD

**Issue by arh1** [forumone/web-starter#260]
Per HipChat today...

We're currently a little ambiguous in whether/how we support multiple sites/hostnames.
- site_url is defined as an array in config/deploy/{stage}.rb
- in lib/capistrano/tasks/web.rake we use site_url in Varnish bans, iterating over each element
- in lib/capistrano/tasks/drush.rake we use it in Drush operations, sometimes using the first element, sometimes iterating over each element. It seems that this logic was built for a pretty specific use case: a multisite installation, where sites are in the same db with different prefixes.

This won't work as expected in other use cases:
- multisite installations with separate dbs <- e.g. drush updb will just get the first database (there may be other web-starter customization needed for this, but still)
- situations where multiple hostnames are used other than multisite <- e.g. many Drush operations will be unnecessarily run repeatedly

Solutions generally seem to be:
- Have our Yeoman generators ask a few questions about multiple hostnames and whether they correspond to multiple databases and make some changes here based on the input
- Assume we're dealing with a single hostname and single db, and provide docs for customization options for other scenarios

Even if we do nothing here any time soon, I hope these notes prove helpful!

**Comment by arh1** [comment]
Just to list them here for discussion:

We iterate over all defined "sites" (hostnames) for:
- varnish bans based on hostname
- Drush updatedb
- Drush cc all / cr
- Drush fr/fra

We use the first defined site for:
- Drush sql-sync
- Drush rsync
- Drush sql-dump

Neither (oops -- looks like a bug unless I'm not reading it right):
- Drush config-sync

**Comment by fafnirical** [comment]
Any updates regarding this? I'm updating web-starter on [forumone/Gates-GrandChallenges-Dev](https://github.com/forumone/Gates-GrandChallenges-Dev) and running into some related issues.

**Comment by mshade** [comment]
I can't speak to the drush and capistrano stuff, but I can say the salt based web starter formulas support multiple vhosts and multiple DBs with a little manual tweaking. If you are using shared codebase, no modifications to nginx should be necessary -- any hostname will route to the default vagrant.conf, ans passed along via HOST header to the site. You can simply add another DB by copying the DB defaults to project.sls and adding another, like so (2 DBs, one DB user defined): 

```yaml
mysql:                                                                          
  mysql_version: mysql56u                                                       
  database:                                                                     
    - web
# Added                                                                   
    - newdb                                                                     
  user:                                                                         
    web:                                                                        
      password: 'web'                                                           
      host: '%'                                                                 
      databases:                                                                
        - database: web                                                         
          grants: ['all privileges']
# Added                                          
        - database: newdb                                                         
          grants: ['all privileges']  
```

This could be added as a question in the generator. I'll assign the task to myself so someone is looking at it.

What are you running into in particular -- anything immediate beyond the vhost and database considerations?
