### ISSUE TITLE
forumone::ssh_config doesn't insert line breaks between hosts

### ISSUE THREAD

**Issue by ohthehugemanatee** [forumone/web-starter#30]
I set up for ACTIAC with this in puppet/manifests/hieradata/sites/localhost.localdomain.yaml :

```
forumone::ssh_config:
  dev.actiac.org:
    hostname: "dev.actiac.com"
    unix_user: "vagrant"
    remote_user: "actiac"
    forward_agent: "yes"
    port: 22
  staging.actiac.org:
    hostname: "staging.actiac.com"
    unix_user: "vagrant"
    remote_user: "actiac"
    forward_agent: "yes"
    port: 22
```

Which generated ~vagrant/.ssh/config like this:

```
Host staging.actiac.org
  HostName staging.actiac.org
  Port 22
  User actiac


  ForwardAgent yesHost dev.actiac.org
  HostName staging.actiac.org
  Port 22
  User actiac


  ForwardAgent yes
```

First of all, I'm not sure where the two blank carriage returns come from in the middle of the host declaration. More importantly, ForwardAgent is missing one.
